### PR TITLE
types: remove StopReason

### PR DESCRIPTION
**Pull request by nuid64**
#22

### CODE REVIEW

**Comment by sztomi** [comment]
Thanks! In the commit message, could you mention that it's being removed in favor of `StoppedEventReason`? So something like

```
types: remove StopReason 

This is being removed in favor of StoppedEventReason;
see https://github.com/sztomi/dap-rs/issues/22
```

This makes it easier to find context outside github.

**Comment by nuid64** [comment]
Commit message length limit is 50 symbols, so I can't add a link to the issue

**Comment by sztomi** [comment]
No, there is no such limitation. Many tools warn about the subject line exceeding 50 chars (which is the first line), but that should be allowed still (and I'm not asking you to change the subject line).

**Comment by nuid64** [comment]
Thanks for the information. My life was a lie.

**Pull request merged**
