### PR TITLE
responses: flatten ResponseMessage member

### PR DESCRIPTION
**Pull request by sztomi**
Fixes #14 

There is a new pre-defined value for `message` in the specification and I figured it doesn't hurt to add:

```ts
  /**
   * Contains the raw error in short form if `success` is false.
   * This raw error might be interpreted by the client and is not shown in the
   * UI.
   * Some predefined values exist.
   * Values: 
   * 'cancelled': the request was cancelled.
   * 'notStopped': the request may be retried once the adapter is in a 'stopped'
   * state.
   * etc.
   */
  message?: 'cancelled' | 'notStopped' | string;
```

### CODE REVIEW

**Comment by sztomi** [comment]
On that note, I filed https://github.com/sztomi/dap-rs/issues/17

**Comment by pileghoff** [comment]
After merging the changes from #19 the error messages now work as expected 👍🏽 But, i think this could be done much simpler way:
```rust
#[derive(Serialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
#[cfg_attr(feature = "integration_testing", derive(Dummy))]
pub enum ResponseMessage {
  /// Should be sent when the request was canceled
  Cancelled,
  /// The request may be retried once the adapter is in a 'stopped' state.
  NotStopped,
  /// Contains the raw error in short form if [`Response::success`](Response::success) is false.
  /// This raw error might be interpreted by the client and is not shown in the UI.
  #[serde(untagged)]
  Error(String),
}
```

That way, we don't need the macro (unless i misunderstand the macro that is).

**Comment by sztomi** [comment]
Indeed, I just learned about the possibility of applying `serde(untagged)` to individual enum variants from @nuid64 in the other PR. I'll get rid of the complication and update this PR.

**Review by pileghoff — APPROVED** [review]

**Comment by sztomi** [comment]
Thanks!

**Pull request merged**
