### PR TITLE
"InitializeArguments " de-serliasation error 

### PR DESCRIPTION
**Pull request by eranif**
- de-serialise adapter_id from "adapterID"
- de-serialise client_id from "clientID"

### CODE REVIEW

**Comment by eranif** [comment]
See the spec here:
https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Initialize
 closes: https://github.com/sztomi/dap-rs/issues/1

**Comment by sztomi** [comment]
Hello, thank you for your PR! I'm a little swamped right now, but I will get back to you this weekend!

**Comment by sztomi** [comment]
I appreciate the initiatives, but please break this up into separate PRs, there are lots of different proposals here. To name a few:

  * [e37126d](https://github.com/sztomi/dap-rs/pull/2/commits/e37126dc5e98adc3def440c78f78a607582be6c2) and [d4182fd](https://github.com/sztomi/dap-rs/pull/2/commits/d4182fdc72f9833baefa97b6e25aba841602dba5) I'm happy to merge these 
  * [6a55b8f](https://github.com/sztomi/dap-rs/pull/2/commits/6a55b8f030331984532d7d7dd48abf2deaead8cf) Happy to merge, but there should be a feature flag that enables implementation-specific fields
  * [c19ce67](https://github.com/sztomi/dap-rs/pull/2/commits/c19ce67fd1e8f711d2abbd70c865158bb1d4a714) There has to be a middle-ground between supporting a specific implementation and the actual spec. If nothing else, a feature flag should toggle this
  * [6dc1505](https://github.com/sztomi/dap-rs/pull/2/commits/6dc150522550485be6547623d4ec3d3310d83cfb) If you can demonstrate a tangible performance benefit for async, I'm open to the idea but I wrote this with blocking code for a reason. For the I/O that a DAP server has to perform it is very likely that async provides no benefit, at the expense of more complicated usage and more difficult debugging.

**Comment by eranif** [comment]
Yes, sure, I was not aware that the PR is updated for each commit I am doing on my branch ...

**Pull request closed without merging**
